apiVersion: v1
kind: Service
metadata:
  name: k8s-employee-management
spec:
  selector:
    app: k8s-employee-management
  ports:
    - name: http
      port: 80
      targetPort: 8091
  type: NodePort